import React from 'react';
import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { parseRecordToReading, getCurrentGoogleUser } from '../src/services/firebaseService';
import { isReadingFresh } from '../src/services/deviceStatus';
import { VietnamAddressFields, isValidGardenAddress } from '../src/components/VietnamAddressFields';
import { DeviceTab } from '../src/views/DeviceTab';
import { AIAssistantTab } from '../src/views/AIAssistantTab';
import { DEFAULT_GARDEN } from '../src/services/demoDataService';
import catalog from '../src/data/vietnam-addresses.json';

Object.assign(globalThis, { localStorage: { getItem: () => null } });
const now = Date.now();
assert.equal(isReadingFresh(0, now), false);
assert.equal(isReadingFresh(now + 1, now), false);
assert.equal(isReadingFresh(now - 300001, now), false);
assert.equal(isReadingFresh(now - 300000, now), true);
const record = { device_id: 'esp32-01', ts: now, values: { ph: 0, ec: 0, moisture: 0, temp: 0 } };
const parsed = parseRecordToReading(record);
assert.equal(parsed.online, true);
assert.equal(parsed.data?.ec, 0);
assert.equal(parsed.data?.ph, 0);
assert.equal(parseRecordToReading({ ...record, ts: undefined }).online, false);
assert.equal(parseRecordToReading({ ...record, ts: now - 31 * 60000 }).online, false);
assert.equal(parseRecordToReading({ ...record, device_id: '' }).success, false);
assert.equal(parseRecordToReading({ ...record, values: { ph: 6 } }).success, false);
assert.equal(parseRecordToReading({ ...record, values: { ...record.values, ec: 50 } }).data?.ec, 0.05);

assert.equal(catalog.provinces.length, 34);
assert.equal(catalog.provinces.reduce((sum,p) => sum+p.wards.length, 0), 3321);
const cantho = catalog.provinces.find(p => p.code === 92)!;
assert.equal(cantho.wards.length, 103);
assert.equal(new Set(catalog.provinces.flatMap(p => p.wards.map(w => w.code))).size, 3321);
const ward = cantho.wards.find(w => w.name === 'Phường Ninh Kiều')!;
assert.ok(ward);
const address = { province: cantho.name, provinceCode: 92, district: '', ward: ward.name, wardCode: ward.code };
assert.equal(isValidGardenAddress(address), true);
assert.equal(isValidGardenAddress({ ...address, provinceCode: 1 }), false);
const locations = renderToStaticMarkup(<VietnamAddressFields value={address} onChange={() => {}} />);
assert.ok(locations.includes('Phường Ninh Kiều'));
assert.ok(!locations.includes('Phường Ba Đình'));
assert.ok(!locations.includes('Huyện / Quận'));

const unverified = { ...DEFAULT_GARDEN, hasVerifiedReading: false, online: false, lastUpdated: 0 };
const device = renderToStaticMarkup(<DeviceTab garden={unverified} syncStatus="disconnected" onUpdateGarden={() => {}} />);
assert.ok(device.includes('Chưa xác nhận kết nối thiết bị'));
assert.ok(device.includes('Chưa kết nối được Firebase'));
assert.ok(!device.includes('Sóng tốt'));
assert.ok(!device.includes('Tín hiệu tốt'));
assert.ok(!device.includes('Đồng bộ tức thì'));
assert.ok(!device.includes('Máy chủ Firebase trực tuyến'));
const chat = renderToStaticMarkup(<AIAssistantTab garden={unverified} />);
assert.ok(chat.includes('Bạn muốn trao đổi điều gì?'));
assert.ok(!chat.includes('Vấn đề hiện tại:'));
assert.ok(!chat.includes('Chào chú chủ vườn'));
assert.equal(await getCurrentGoogleUser(), null, 'No config or session must not create an authenticated user');
console.log('PASS: device freshness and missing data, 34/3321 address catalog, Can Tho 103 wards, offline UI, empty chat, unauthenticated startup.');
