import assert from 'node:assert/strict';
import { applyRealtimeToTree } from '../src/services/saveRealtimeTree';
import { roomStorageService } from '../src/services/roomStorageService';
import { Garden } from '../src/types';

const values = new Map<string, string>();
Object.assign(globalThis, { localStorage: { getItem: (k: string) => values.get(k) ?? null, setItem: (k: string, v: string) => values.set(k, v) }, window: new EventTarget() });
const garden = { id: 'g1', deviceId: 'esp32-01' } as Garden;
const first = { id: 't1', gardenId: 'g1', name: 'Cây 1', spotNumber: 1, variety: 'Ri6', treeAge: 3, height: 2, canopyWidth: 2 };
const second = { ...first, id: 't2', name: 'Cây 2' };
roomStorageService.addOrUpdateTreeLocation(first);
roomStorageService.addOrUpdateTreeLocation(second);
const now = Date.now();
const reading = { key: '-key1', deviceId: 'esp32-01', ts: now - 1000, ph: 6.21, ec: 216, moisture: 12.3, temp: 26.4 };
applyRealtimeToTree(garden, first, reading, now);
let saved = roomStorageService.getTreeLocations('g1').find(t => t.id === 't1')!;
assert.equal(saved.lastPh, 6.21);
assert.equal(saved.lastEc, 0.216);
assert.equal(saved.lastMoisture, 12.3);
assert.equal(saved.lastTemp, 26.4);
assert.equal(saved.lastMeasuredAt, reading.ts);
assert.equal(roomStorageService.getMeasurements('g1', 't1').length, 1);
assert.throws(() => applyRealtimeToTree(garden, first, reading, now), /đã có số đo/);
assert.throws(() => applyRealtimeToTree(garden, second, reading, now), /cây khác/);
assert.throws(() => applyRealtimeToTree(garden, second, { ...reading, ts: now - 6 * 60000 }, now), /Chưa có số đo mới/);
applyRealtimeToTree(garden, first, { ...reading, key: '-key2', ts: now, ph: 6.4 }, now);
saved = roomStorageService.getTreeLocations('g1').find(t => t.id === 't1')!;
assert.equal(saved.lastPh, 6.4);
assert.equal(roomStorageService.getMeasurements('g1', 't1').length, 2);
assert.equal(roomStorageService.getMeasurements('g1', 't1')[0].syncedToCloud, false);
assert.equal(roomStorageService.getTreeLocations('g1').find(t => t.id === 't2')?.lastPh, undefined);
console.log('PASS: immediate selected-tree values/history, raw EC conversion, new data replaces old, duplicate/stale/cross-tree rejection.');
